CREATE TABLE restaurant_operate_log (
                                        id BIGINT NOT NULL AUTO_INCREMENT COMMENT '操作日志编号',
                                        biz_type VARCHAR(50) NOT NULL COMMENT '业务类型：DIVIDEND_PERIOD、REVENUE_IMPORT、COST_IMPORT 等',
                                        biz_id BIGINT DEFAULT NULL COMMENT '业务编号',
                                        store_id BIGINT DEFAULT NULL COMMENT '门店编号',
                                        dept_id BIGINT DEFAULT NULL COMMENT '部门编号',
                                        period_id BIGINT DEFAULT NULL COMMENT '分红账期编号',
                                        period_month VARCHAR(7) DEFAULT NULL COMMENT '账期月份，例如 2026-06',
                                        operate_type VARCHAR(50) NOT NULL COMMENT '操作类型',
                                        before_status TINYINT DEFAULT NULL COMMENT '操作前状态',
                                        after_status TINYINT DEFAULT NULL COMMENT '操作后状态',
                                        operate_user_id BIGINT DEFAULT NULL COMMENT '操作人编号',
                                        operate_time DATETIME NOT NULL COMMENT '操作时间',
                                        remark VARCHAR(1000) DEFAULT NULL COMMENT '操作备注',
                                        creator VARCHAR(64) DEFAULT '' COMMENT '创建者',
                                        create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                        updater VARCHAR(64) DEFAULT '' COMMENT '更新者',
                                        update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                        deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
                                        tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
                                        PRIMARY KEY (id),
                                        KEY idx_biz_type_biz_id (biz_type, biz_id),
                                        KEY idx_store_id (store_id),
                                        KEY idx_dept_id (dept_id),
                                        KEY idx_period_id (period_id),
                                        KEY idx_period_month (period_month),
                                        KEY idx_operate_type (operate_type),
                                        KEY idx_operate_user_id (operate_user_id),
                                        KEY idx_operate_time (operate_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='餐饮业务操作日志表';