CREATE TABLE restaurant_dividend_approve_record (
                                                    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '审批记录编号',
                                                    period_id BIGINT NOT NULL COMMENT '分红账期编号',
                                                    store_id BIGINT NOT NULL COMMENT '门店编号',
                                                    dept_id BIGINT NOT NULL COMMENT '部门编号',
                                                    period_month VARCHAR(7) NOT NULL COMMENT '账期月份，例如 2026-06',
                                                    approve_status TINYINT NOT NULL COMMENT '审批状态：0审批中 1审批通过 2审批驳回',
                                                    submit_user_id BIGINT DEFAULT NULL COMMENT '提交人编号',
                                                    submit_time DATETIME DEFAULT NULL COMMENT '提交时间',
                                                    approve_user_id BIGINT DEFAULT NULL COMMENT '审批人编号',
                                                    approve_time DATETIME DEFAULT NULL COMMENT '审批时间',
                                                    approve_reason VARCHAR(500) DEFAULT NULL COMMENT '审批意见',
                                                    remark VARCHAR(1000) DEFAULT NULL COMMENT '备注',
                                                    creator VARCHAR(64) DEFAULT '' COMMENT '创建者',
                                                    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                    updater VARCHAR(64) DEFAULT '' COMMENT '更新者',
                                                    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                    deleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
                                                    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
                                                    PRIMARY KEY (id),
                                                    KEY idx_period_id (period_id),
                                                    KEY idx_store_id (store_id),
                                                    KEY idx_dept_id (dept_id),
                                                    KEY idx_period_month (period_month),
                                                    KEY idx_approve_status (approve_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分红发放审批记录表';